export const categories = [
  {
    rows: 84,
    columns: ["Ürünler", "Açılış", "Gelen", "Toplam", "Tadım", "Atık", "Satış", "Kapanış", "Fark", "Ürün Bitiş Saati"],
    alt: [
      "TAHILLI POĞAÇA", "DİL PEYNİRLİ ROMASCO PİDE", "AÇMA ÇİKOLATALI", "KURUVASAN CAPRESE", 
      "PEYNİRLİ ÇÖREK", "TEREYAĞLI KRUVASAN", "ANNE POĞAÇA", "HELLİMLİ ZEYTİNLİ POĞAÇA", "ZEYTİNLİ AÇMA","DANA FÜMELİ BAGEL SANDVİÇ", "PEYNİRLİ SİMİT SANDVİÇ", "ESLAB MİNİ MİX SANDVİÇ", 
      "3 PEYNİRLİ & AVAKADOLU SANDVİÇ", "KOREAN CHİCKEN SANDVİÇ", "KUKİ YULAFLI ÜZÜMLÜ", "ÇİKOLATALI LEVAİN", "KUKİ LEVAİN", "KUKİ ANTEP FISTIKLI",
      "KEK HAVUÇ", "KEK LİMONLU", "KEK MERMER", "STRAWBERRY SHORTCAKE", "İZMİR BOMBA", 
      "ÇİKOLATALI FISTIKLI PROFİTEROL", "TİRAMİSU", "ANTEP FISTIKLI PROFİTEROL", "MUZLU CİCİBEBELİ", 
      "VEGAN ELMA BAR", "KEK BEYAZ BROWNİ", "CİNNAMON CUPCAKE", "FINDIKLI PARİS BREST", 
      "FİNANCİER", "MONT BLAC", "MUZLU RULO", "MUZLU PUF", "DUBAİ ÇİKOLATASI", "MOZAİK PASTA", 
      "LİMONLU EKLER", "FRAMBUAZ DOLGULU DONUT", "KARAMLE DOLGULU DONUT", "EKLER ÇİKOLATALI", 
      "CHİA PUDİNG GRANOLA","SUPER OREO CHEESECAKE", "RED VELVET CHEESECAKE", "LOTUS CHEESECAKE", "SAN SEBASTİAN CHEESECAKE","RED VELVET KUKİ MİNİ", "ÇİKOLATALI SABLE", "POPCORN CARAMEL", "SİYAH ZEYTİNLİ KURABİYE", 
      "CARAMEL WAFFLE İKİLİ", "ESLAB KURUYEMİŞ", "MOMS BROWNİE", "ESLAB GOFRET", "KALE CİPSİ", 
      "PANCAR CİPSİ", "LEBLEBİ ZEYTİNLİ", "BALLI SUSAMLI", "MOMS PEANUT", "MOMS LEMON", "KAKAO BROWNİ", 
      "KAKAO BAR", "COLAGEN KROKAN", "KURUTULMUŞ ÇİLEK", "KURUTULMUŞ ELMA", "KURUTULMUŞ İNCİR","SANPELLEGRİNO", "SANPELLEGRİNO LİMONATA", "SANPELLEGRİNO ARANCİATA ROSSA", 
      "SANPELLEGRİNO PLAİN", "PFANER ACE", "SU CAM ŞİŞE", "SU PET ŞİŞE", "COLD BREW", 
      "MADEN SUYU", "PFANNER ÇİLEK", "ARİZONA BLUEBERRY", "ARİZONA PEACH", "PFANNER YEŞİL ELMA", 
      "FİJİ SU", "CHURCİLL", "ULUDAĞ SU", "KOMBUCHA ZENCEFİL", "KOMBUCHA SADE",
    ],
  },
];
